import React from 'react'
import Head from 'next/head'
import CookieStandHeader from './header'
import CookieStandMain from './main'
import CookieStandFooter from './footer'
import { useState } from 'react'

export default function CookieStandAdmin() {
    const [locations,setLocations] = useState('0')
    return (
        <div>
        <Head>
          <title>Cookie Stand Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>  
  
        <CookieStandHeader/>
        
        
        <CookieStandMain setLocations={setLocations}/>
        <CookieStandFooter locations={locations}/>
      </div>
    )
}

