import React from 'react'
import Head from 'next/head'
import CookieStandHeader from './header'
import CookieStandMain from './main'
import CookieStandFooter from './footer'
// import {useEffect, useState}from 'react'
// import {workHours} from'../data'

export default function CookieStandAdmin() {
    return (
        <div>
        <Head>
          <title>Cookie Stand Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>  
        <CookieStandHeader/>
        <CookieStandMain/>
        <CookieStandFooter/>
      </div>
    )
}
