import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CookieStandHeader from '../components/header'
import CookieStandFooter from '../components/footer' 
import CookieStandMain from '../components/main'


export default function Home() {
  return (
    <div className={styles.container}>
    <Head>
      <title>Cookie Stand Admin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>  

    <CookieStandHeader/>
    
    <CookieStandMain/>
    <p>Report Table comming soon .....</p>
    <CookieStandFooter/>
  </div>
      
  )
}
